# Generated by Django 4.2 on 2023-04-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(unique=True, upload_to='images/')),
                ('title', models.CharField(max_length=520, unique=True)),
                ('description', models.TextField(unique=True)),
                ('date', models.DateField(unique=True)),
            ],
        ),
    ]
