# Generated by Django 4.2 on 2023-05-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_doctor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Yangiliklar',
        ),
    ]
