# Generated by Django 4.2 on 2023-05-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_news_yangiliklar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Biz_haqimizda',
        ),
        migrations.RenameModel(
            old_name='Home',
            new_name='Bosh_sahifa',
        ),
        migrations.RenameModel(
            old_name='Doctor',
            new_name='Shifokorlar',
        ),
    ]
