# Generated by Django 4.2 on 2023-05-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_about_biz_haqimizda_rename_home_bosh_sahifa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kassalliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(unique=True, upload_to='images/')),
                ('title', models.CharField(max_length=520, unique=True)),
                ('description', models.TextField(unique=True)),
                ('date', models.DateField(unique=True)),
            ],
        ),
    ]
