# Generated by Django 4.2 on 2023-05-13 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_kassalliklar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biz_haqimizda',
            options={'verbose_name_plural': 'Biz haqimizda'},
        ),
    ]
