# Generated by Django 4.2 on 2023-05-13 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_biz_haqimizda_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bosh_sahifa',
            options={'verbose_name_plural': 'Bosh sahifa'},
        ),
        migrations.AlterModelOptions(
            name='kassalliklar',
            options={'verbose_name_plural': 'Kassalliklar'},
        ),
        migrations.AlterModelOptions(
            name='shifokorlar',
            options={'verbose_name_plural': 'Shifokorlar'},
        ),
        migrations.AlterModelOptions(
            name='yangiliklar',
            options={'verbose_name_plural': 'Yangiliklar'},
        ),
    ]
