# Generated by Django 4.2 on 2023-05-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_bosh_sahifa_options_alter_kassalliklar_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tozalik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=520, unique=True)),
                ('cover', models.ImageField(unique=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Tozalik Qoidalari',
            },
        ),
    ]
