# Generated by Django 4.2 on 2023-05-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_tozalik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tavsifnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=520, unique=True)),
                ('description', models.TextField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tavsifnoma',
            },
        ),
    ]
