# Generated by Django 4.2 on 2023-05-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_tavsifnoma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tavsifnoma',
            options={'verbose_name_plural': 'Tavsifnomalar'},
        ),
    ]
