# Generated by Django 4.2 on 2023-05-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_tavsifnoma_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qarashlarimiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=520, unique=True)),
                ('description', models.TextField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Qarashlarimiz',
            },
        ),
    ]
